### ISSUE TITLE
[OXMSG] Usage

### ISSUE THREAD

**Issue by yok0** [xianhammer/format#1]
Hi. I'm new to go and still confused. Would it be possible for you to provide simple 
docs on the usage of the OXMSG module please?

**Comment by xianhammer** [comment]
Hi Adam.

The OXMSG part is barely working and not even close to being complete. So currently there is no real value describing what it does and how it works.

It relies on the also-not-complete CFB project and trying to understand Microsoft (their format) is a bit of a trial.

I cannot make any promises to when I'll continue OXMSG and CFB.

**Comment by yok0** [comment]
I read the OXMSG format doc myself and it's just over my head. Thanks for the update and good luck.

Just FYI, https://www.fileformat.info/format/outlookmsg/ - seems to be easier on my brain than the official spec.
